// protoc --go_out=. ./cmd/shiroxy/users/user_models.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: cmd/shiroxy/users/user_models.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email          string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	HashedPassword string `protobuf:"bytes,4,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shiroxy_users_user_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shiroxy_users_user_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_cmd_shiroxy_users_user_models_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

type ShutDownBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsUser          bool   `protobuf:"varint,1,opt,name=is_user,json=isUser,proto3" json:"is_user,omitempty"`
	UserId          string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShutdownMessage string `protobuf:"bytes,3,opt,name=shutdown_message,json=shutdownMessage,proto3" json:"shutdown_message,omitempty"`
}

func (x *ShutDownBy) Reset() {
	*x = ShutDownBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shiroxy_users_user_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutDownBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutDownBy) ProtoMessage() {}

func (x *ShutDownBy) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shiroxy_users_user_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutDownBy.ProtoReflect.Descriptor instead.
func (*ShutDownBy) Descriptor() ([]byte, []int) {
	return file_cmd_shiroxy_users_user_models_proto_rawDescGZIP(), []int{1}
}

func (x *ShutDownBy) GetIsUser() bool {
	if x != nil {
		return x.IsUser
	}
	return false
}

func (x *ShutDownBy) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShutDownBy) GetShutdownMessage() string {
	if x != nil {
		return x.ShutdownMessage
	}
	return ""
}

type ShutDownDataPersistance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShutdownDatetime      string      `protobuf:"bytes,1,opt,name=shutdown_datetime,json=shutdownDatetime,proto3" json:"shutdown_datetime,omitempty"`
	ShutdownBy            *ShutDownBy `protobuf:"bytes,2,opt,name=shutdown_by,json=shutdownBy,proto3" json:"shutdown_by,omitempty"`
	TotalDomainAtShutdown int32       `protobuf:"varint,3,opt,name=total_domain_at_shutdown,json=totalDomainAtShutdown,proto3" json:"total_domain_at_shutdown,omitempty"`
	TotalUserAtShutdown   int32       `protobuf:"varint,4,opt,name=total_user_at_shutdown,json=totalUserAtShutdown,proto3" json:"total_user_at_shutdown,omitempty"`
	MemoryVirt            int32       `protobuf:"varint,5,opt,name=memory_virt,json=memoryVirt,proto3" json:"memory_virt,omitempty"`
	MemoryRes             int32       `protobuf:"varint,6,opt,name=memory_res,json=memoryRes,proto3" json:"memory_res,omitempty"`
	MemoryShr             int32       `protobuf:"varint,7,opt,name=memory_shr,json=memoryShr,proto3" json:"memory_shr,omitempty"`
	CpuUsage              int32       `protobuf:"varint,8,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	GcCount               int32       `protobuf:"varint,9,opt,name=gc_count,json=gcCount,proto3" json:"gc_count,omitempty"`
	Pid                   int32       `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *ShutDownDataPersistance) Reset() {
	*x = ShutDownDataPersistance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shiroxy_users_user_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutDownDataPersistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutDownDataPersistance) ProtoMessage() {}

func (x *ShutDownDataPersistance) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shiroxy_users_user_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutDownDataPersistance.ProtoReflect.Descriptor instead.
func (*ShutDownDataPersistance) Descriptor() ([]byte, []int) {
	return file_cmd_shiroxy_users_user_models_proto_rawDescGZIP(), []int{2}
}

func (x *ShutDownDataPersistance) GetShutdownDatetime() string {
	if x != nil {
		return x.ShutdownDatetime
	}
	return ""
}

func (x *ShutDownDataPersistance) GetShutdownBy() *ShutDownBy {
	if x != nil {
		return x.ShutdownBy
	}
	return nil
}

func (x *ShutDownDataPersistance) GetTotalDomainAtShutdown() int32 {
	if x != nil {
		return x.TotalDomainAtShutdown
	}
	return 0
}

func (x *ShutDownDataPersistance) GetTotalUserAtShutdown() int32 {
	if x != nil {
		return x.TotalUserAtShutdown
	}
	return 0
}

func (x *ShutDownDataPersistance) GetMemoryVirt() int32 {
	if x != nil {
		return x.MemoryVirt
	}
	return 0
}

func (x *ShutDownDataPersistance) GetMemoryRes() int32 {
	if x != nil {
		return x.MemoryRes
	}
	return 0
}

func (x *ShutDownDataPersistance) GetMemoryShr() int32 {
	if x != nil {
		return x.MemoryShr
	}
	return 0
}

func (x *ShutDownDataPersistance) GetCpuUsage() int32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ShutDownDataPersistance) GetGcCount() int32 {
	if x != nil {
		return x.GcCount
	}
	return 0
}

func (x *ShutDownDataPersistance) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_cmd_shiroxy_users_user_models_proto protoreflect.FileDescriptor

var file_cmd_shiroxy_users_user_models_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x68, 0x69, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x69, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x27, 0x0a,
	0x0f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x69, 0x0a, 0x0a, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f,
	0x77, 0x6e, 0x42, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x90, 0x03, 0x0a, 0x17, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2b, 0x0a,
	0x11, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x73, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x42,
	0x79, 0x52, 0x0a, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x42, 0x79, 0x12, 0x37, 0x0a,
	0x18, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x61, 0x74,
	0x5f, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x15, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x41, 0x74, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x33, 0x0a, 0x16, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x5f, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x74, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x56, 0x69, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x68, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x68, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70,
	0x75, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x63, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x63, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x70, 0x69, 0x64, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x68,
	0x69, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cmd_shiroxy_users_user_models_proto_rawDescOnce sync.Once
	file_cmd_shiroxy_users_user_models_proto_rawDescData = file_cmd_shiroxy_users_user_models_proto_rawDesc
)

func file_cmd_shiroxy_users_user_models_proto_rawDescGZIP() []byte {
	file_cmd_shiroxy_users_user_models_proto_rawDescOnce.Do(func() {
		file_cmd_shiroxy_users_user_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_shiroxy_users_user_models_proto_rawDescData)
	})
	return file_cmd_shiroxy_users_user_models_proto_rawDescData
}

var file_cmd_shiroxy_users_user_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_shiroxy_users_user_models_proto_goTypes = []any{
	(*User)(nil),                    // 0: main.User
	(*ShutDownBy)(nil),              // 1: main.ShutDownBy
	(*ShutDownDataPersistance)(nil), // 2: main.ShutDownDataPersistance
}
var file_cmd_shiroxy_users_user_models_proto_depIdxs = []int32{
	1, // 0: main.ShutDownDataPersistance.shutdown_by:type_name -> main.ShutDownBy
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_shiroxy_users_user_models_proto_init() }
func file_cmd_shiroxy_users_user_models_proto_init() {
	if File_cmd_shiroxy_users_user_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_shiroxy_users_user_models_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shiroxy_users_user_models_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShutDownBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shiroxy_users_user_models_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ShutDownDataPersistance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_shiroxy_users_user_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_shiroxy_users_user_models_proto_goTypes,
		DependencyIndexes: file_cmd_shiroxy_users_user_models_proto_depIdxs,
		MessageInfos:      file_cmd_shiroxy_users_user_models_proto_msgTypes,
	}.Build()
	File_cmd_shiroxy_users_user_models_proto = out.File
	file_cmd_shiroxy_users_user_models_proto_rawDesc = nil
	file_cmd_shiroxy_users_user_models_proto_goTypes = nil
	file_cmd_shiroxy_users_user_models_proto_depIdxs = nil
}
